// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpJYJFx1qo6sAiFpwSxaNpueBHnQFYC88',
    appId: '1:735091795901:web:5c54d63bc3bf810b6354d4',
    messagingSenderId: '735091795901',
    projectId: 'aplikasi-aset-kominfo-9482d',
    authDomain: 'aplikasi-aset-kominfo-9482d.firebaseapp.com',
    storageBucket: 'aplikasi-aset-kominfo-9482d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmrLDCd_ydnV97Up1gdX22C-36SG4ags',
    appId: '1:735091795901:android:4e67a490108fb01d6354d4',
    messagingSenderId: '735091795901',
    projectId: 'aplikasi-aset-kominfo-9482d',
    storageBucket: 'aplikasi-aset-kominfo-9482d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpJYJFx1qo6sAiFpwSxaNpueBHnQFYC88',
    appId: '1:735091795901:web:08837ac3f46eafa16354d4',
    messagingSenderId: '735091795901',
    projectId: 'aplikasi-aset-kominfo-9482d',
    authDomain: 'aplikasi-aset-kominfo-9482d.firebaseapp.com',
    storageBucket: 'aplikasi-aset-kominfo-9482d.firebasestorage.app',
  );
}
